---
version: '3.3'

services:

  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden_rs
    restart: unless-stopped
    volumes:
      - /srv/docker/bitwarden:/data
    environment:
      - "ADMIN_TOKEN=${ADMIN_TOKEN}"
      - "WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.bitwarden.entrypoints=web-secure"
      
      # ui
      - "traefik.http.routers.bitwarden.rule=Host(`${BITWARDEN_DOMAIN}`)"
      - "traefik.http.routers.bitwarden.tls=true"
      - "traefik.http.routers.bitwarden.tls.certresolver=default"
      - "traefik.http.routers.bitwarden.service=bitwarden-ui"
      - "traefik.http.services.bitwarden-ui.loadbalancer.server.port=80"

      # admin console
      - "traefik.http.routers.bitwarden-admin.rule=Host(`${BITWARDEN_DOMAIN}`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.bitwarden-admin.tls=true"
      - "traefik.http.routers.bitwarden-admin.service=admin-panel"
      - "traefik.http.services.admin-panel.loadbalancer.server.port=80"
      - "traefik.http.routers.bitwarden-admin.tls.certresolver=default"
      - "traefik.http.middlewares.admin-auth.basicauth.users=${ADMIN_USER_PW}"
      - "traefik.http.routers.bitwarden-admin.middlewares=admin-auth"

      # notifications hub
      - "traefik.http.routers.bitwarden-websocket.rule=Host(`${BITWARDEN_DOMAIN}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket.tls=true"
      - "traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket"
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"

    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
