---
version: '3.3'

services:

  bitwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /srv/docker/bitwarden:/data
    environment:
      - "ADMIN_TOKEN=${ADMIN_TOKEN}"
      - "WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.bitwarden.entrypoints=web-secure"

      # ui
      - "traefik.http.routers.vaultwarden.rule=Host(`${BITWARDEN_DOMAIN}`)"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.tls.certresolver=default"
      - "traefik.http.routers.vaultwarden.service=vaultwarden-ui"
      - "traefik.http.services.vaultwarden-ui.loadbalancer.server.port=80"

      # admin console
      - "traefik.http.routers.vaultwarden-admin.rule=
         Host(`${BITWARDEN_DOMAIN}`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.vaultwarden-admin.tls=true"
      - "traefik.http.routers.vaultwarden-admin.service=admin-panel"
      - "traefik.http.services.admin-panel.loadbalancer.server.port=80"
      - "traefik.http.routers.vaultwarden-admin.tls.certresolver=default"
      - "traefik.http.middlewares.admin-auth.basicauth.users=${ADMIN_USER_PW}"
      - "traefik.http.routers.vaultwarden-admin.middlewares=admin-auth"

      # notifications hub
      - "traefik.http.routers.vaultwarden-websocket.rule=
         Host(`${BITWARDEN_DOMAIN}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.vaultwarden-websocket.tls=true"
      - "traefik.http.routers.vaultwarden-websocket.service=bitwarden-websocket"
      - "traefik.http.services.vaultwarden-websocket.loadbalancer.server.port=3012"

    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
