---
version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/:/etc/prometheus/
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./config:/prometheus
     # - ./data/alertmanager:/data
    command:
      - '--config.file=/prometheus/alertmanager.yml'
    #  - '--storage.path=/data'
    ports:
      - 9093:9093

  blackbox-exporter:
    image: "prom/blackbox-exporter:latest"
    hostname: "blackbox"
    restart: unless-stopped
    depends_on:
      - "prometheus"
    ports:
      - "9115:9115"
    volumes:
      - "./config/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml"
    command:
      - "--config.file=/etc/prometheus/blackbox-exporter.yml"

  webhook:
    image: thecatlady/webhook
    container_name: webhook
    command: -verbose -hooks=hooks.yml -hotreload
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/:/config/
      - ./data/:/data/
    ports:
      - 9116:9000
    restart: unless-stopped
