---
# See https://prometheus.io/docs/alerting/configuration/ for documentation.

global:

receivers:
  - name: "my-receiver"
    webhook_configs:
      - url: "http://localhost:9116/hooks/echo-webhook"

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: "my-receiver"
