---
# See https://prometheus.io/docs/alerting/configuration/ for documentation.

global:

receivers:
  - name: 'default-receiver'
  - name: 'down_alert_receiver'
    webhook_configs:
      - url: "http://localhost:9116/hooks/down-webhook"
  - name: 'up_alert_receiver'
    webhook_configs:
      - url: "http://localhost:9116/hooks/up-webhook"

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: default-receiver

  routes:
    - match:
        alertname: http_down
      receiver: down_alert_receiver
    - match:
        alertname: http_up
      receiver: up_alert_receiver
