---
# See https://prometheus.io/docs/alerting/configuration/ for documentation.

global:

receivers:
  - name: 'default-receiver'
  - name: 'my-receiver'
    webhook_configs:
      - url: "http://localhost:9116/hooks/echo-webhook"

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: default-receiver

  routes:
    - match_re:
        alertname: service_up
      receiver: my-receiver
