---
version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=traefik_proxy
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --api
#      - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.default.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.default.acme.storage=/config/acme.json
      - --certificatesresolvers.default.acme.tlschallenge=true
      - --log.filePath=/srv/docker/traefik/traefik.log
      - --log.format=json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime
      - "./config:/config"
#      - /srv/docker/traefik/access.log:/srv/docker/traefik/access.log
      - /srv/docker/traefik/traefik.log:/srv/docker/traefik/traefik.log
 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.entryPoints=web-secure"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
#      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=default"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=api-auth"
      - "traefik.http.middlewares.api-auth.basicauth.users=${BASIC_AUTH}" 

    # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

    # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

    networks:
      - traefik_proxy
      - default
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge    
