---
version: '3'
services:
  ouroboros:
    image: pyouroboros/ouroboros:latest
    container_name: ouroboros
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Check interval in seconds... here we go for every 12 hours
      - INTERVAL=43200
      - LOG_LEVEL=error
      - SELF_UPDATE=true
      # to ignore container: provide the respective container name here
      - IGNORE=nextcloud-app nextcloud-db piwigo-app piwigo-db
      - CLEANUP=true
      - TZ=Europe/Berlin
