---
version: '3'
services:
 ouroboros:
    image: pyouroboros/ouroboros:latest
    container_name: ouroboros
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
# Check interval in seconds... here we go for every 12 hours
      - INTERVAL=43200
      - LOG_LEVEL=error
      - SELF_UPDATE=true
# If we wanna ignore container we can do so by providing the container name here
#      - IGNORE=mysql
      - CLEANUP=true
      - TZ=Europe/Berlin
