---
version: '3.3'

services:
  wordpress-db:
    image: hypriot/rpi-mysql
    container_name: wordpress-db
    restart: always
    volumes:
      - /srv/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}

  wordpress-app:
    image: wordpress:latest
    container_name: wordpress-app
    restart: always
    volumes:
      - /srv/www/wp-content:/var/www/html/wp-content
    environment:
      - WORDPRESS_DB_HOST=wordpress-db:3306
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.entrypoints=web-secure"
      - "traefik.http.routers.wordpress.rule=Host(`${TOP_LEVEL_DOMAIN}`) || Host(`${SUB_DOMAIN}`)"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=default"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    networks:
      - default
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
