---
version: '3.3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/portainer:/data
    command: --admin-password="${ADMIN_PASSWD}"
    restart: always

# Comment in, if you wanna proxy portainer via traefik
# (.env file with PORTAINER_DOMAIN as environment variable required)

#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.portainer.entrypoints=web-secure"
#      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_DOMAIN}`)"
#      - "traefik.http.routers.portainer.tls=true"
#      - "traefik.http.routers.portainer.tls.certresolver=default"
