---
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001

networks:
  backend:
    external:
      name: backend
