---
version: "3.3"

services:
  syncthing:
    # image: ghcr.io/linuxserver/syncthing
    image: syncthing/syncthing
    container_name: syncthing

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

    volumes:
      - /srv/syncthing/config:/config
      - /srv/syncthing/data:/data
#      - /srv/syncthing/music:/data/music
#      - /srv/syncthing/album:/data/album

    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp

    restart: unless-stopped
