---
version: "3.3"

services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

    volumes:
      - /srv/syncthing/config:/config
      - /srv/syncthing/data:/data1
      # - /path/to/data2:/data2

    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp

    restart: unless-stopped
