---

groups:
  - name: web.rules
    rules:
      - alert: invalid_http_status_code
        expr: probe_http_status_code != 200
        for: 10m
        labels:
          severity: critical

      # service availability alert
      - alert: service_down
        expr: up == 0
        labels:
          severity: critical

      - alert: service_up
        expr: up == 1
        labels:
          severity: normal
